name: Rust
on:
  push:
  pull_request:
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --check
      - run: cargo check --all-targets
      - run: cargo test
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo build --release
      - run: cargo check --manifest-path fuzz/Cargo.toml --all-targets
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --check
      - run: cargo check --all-targets
      - run: cargo test --all-targets
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo doc --no-deps
      - run: cargo test --doc
      - run: cargo build --release
      - run: cargo package
      - run: cargo publish --dry-run
